name: pp_translator
version: 0.0.2
description: A free and unlimited Google Translate API for Dart. You can use it for translate strings and text for educational purpose.
#author: Gabriel N. Pacheco <gabrielpacheco23@live.com>
homepage: https://github.com/Puja-Purohit/pp-translator
dependencies:
  http: ^1.1.0

dev_dependencies:
  test: any

environment:
  sdk: ">=3.0.0 <4.0.0"
